### ISSUE TITLE
Ability to use ndpi and tiff WSIs

### ISSUE THREAD

**Issue by ajr82** [pacocp/WSI-Pancreas-Classification#3]
Can we use .ndpi and .tiff (Philips) WSIs?

I noticed that the patch_gen_grid.py only mentions .svs WSI. 

Thank you!

**Comment by pacocp** [comment]
Hi! The library used to read the images is Openslide, which apparently allows to use both ndpi (https://openslide.org/formats/hamamatsu/) and tiff files (https://openslide.org/formats/generic-tiff/). However, I have only tested using SVS files, so maybe some modifications are required to make it work. Hope it helps!
